"""verify model imports

Revision ID: 577ce153a6dd
Revises: d79d6778b82e
Create Date: 2025-10-23 09:32:33.315125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577ce153a6dd'
down_revision: Union[str, Sequence[str], None] = 'd79d6778b82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badges', 'icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_index(op.f('ix_interests_id'), 'interests', ['id'], unique=False)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('profiles', 'bio')
    op.drop_constraint(op.f('user_stats_user_id_fkey'), 'user_stats', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_stats_user_id_fkey'), 'user_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('profiles', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_interests_id'), table_name='interests')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.alter_column('badges', 'icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
